# Default Docker Compose config:
# runs GHC Web App (ghc_web) and GHC Daemon Runner (ghc_runner) Docker containers
# with SQLite backend.  ghc_runner will run using the schedule
# configured in the GHC Web App.
#
# Plugins (optional) need to be configured for both Docker containers.
version: "3"

services:
  ghc_web:
    image: geopython/geohealthcheck:latest

    container_name: ghc_web

    restart: unless-stopped

    ports:
      - 8083:80

    env_file:
      - .env

    volumes:
      - ${DATA_DIR}:/GeoHealthCheck/DB
      #- ghc_sqlitedb:/GeoHealthCheck/DB
      # Optional Plugins, using Path on the host, relative to this Compose file
      # To activate: 2 steps for runner and GHC webapp:
      # - configure in .env
      # - mount these as docker volume on host
      # See https://docs.docker.com/compose/compose-file/#volumes
      # - ./../GeoHealthCheck/plugins:/plugins:ro

  ghc_runner:
    image: geopython/geohealthcheck:latest

    container_name: ghc_runner

    restart: unless-stopped

    env_file:
      - .env

    entrypoint:
      - /run-runner.sh

    volumes:
      - ${DATA_DIR}:/GeoHealthCheck/DB
      #- ghc_sqlitedb:/GeoHealthCheck/DB
      # Optional Plugins, using Path on the host, relative to this Compose file
      # To activate 2 steps:
      # - configure in .env
      # - mount these as docker volume on host
      # See https://docs.docker.com/compose/compose-file/#volumes
      # - ./../GeoHealthCheck/plugins:/plugins:ro

# docker-compose v2+ needs separate volumes section
volumes:
  ghc_sqlitedb:
